server:
  port: 8003
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kaeter/spiring-cloud-test/
          search-paths: config-repo
          username: 609223790@qq.com
          password: hkf0611
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/